apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: cartarshop-ingress
  annotations:
    kubernetes.io/ingress.class: alb
spec:
  rules:
  - host: stepin.ink
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: frontend
            port:
              number: 80