name: CI/CD

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    steps:
      - uses: actions/checkout@v3

      - name: Configure AWS (OIDC)
        uses: aws-actions/configure-aws-credentials@v3
        with:
          role-to-assume: <ROLE_ARN>
          aws-region: us-east-1

      - name: Build
        run: docker build -t cartarshop ./services/product-service

      - name: Scan Image
        run: docker run aquasec/trivy image cartarshop

      - name: Push to ECR
        run: |
          aws ecr get-login-password | docker login ...
          docker push <ECR>